### ISSUE TITLE
Mettre à jour liste membres avec photos

### ISSUE THREAD

**Issue by emaulandi** [ToulouseDataViz/website#11]
- [x] vincent
- [ ] tony
- [ ] christophe

Mise à jour des membres @Tony Hauck @Christophe Regouby pourriez vous soit faire vos modifs ou me fournir les éléments ? voir Documentation - Ajouter un membre de l'équipe, et si à l'aise avec github (uniquement interface graphique), vous pouvez suivre ce tuto

**Comment by vvivanloc** [comment]
@XtopheB Merci pour la photo ;) Mais je pense qu'Edith voulait celles de Christophe R.
