### ISSUE TITLE
Fix: improve hackaviz rendering

### ISSUE THREAD

**Issue by vvivanloc** [ToulouseDataViz/website#110]
- transform hackaviz contest into a csv ?
   - pros : simpler to maintain
   - cons: not easily editable

- hachaviz results: improve grid cell rendering
    -    height is not uniform
    -   too much text -> to be elided

**Comment by emaulandi** [comment]
_transform hackaviz contest into a csv ? pros : simpler to maintain_ -> en quoi c'est plus simple à maintenir un csv ? Pour faciliter l'édition par tout un chacun, il me semble que c'est plus simple d'avoir une page .mdx éditable par tout le monde facilement en markdwon.
A la limite on peut créer des composants pour certaines parties (ex: les boutons des newsletter) avec du contenu à rajouter dans data/hackaviz.csv 

Par contre la page de résultat elle pourrait être créée programmatiquement dans un plugin dédiée

**Comment by emaulandi** [comment]
_hachaviz results: improve grid cell rendering. too much text -> to be elided_ -> il est important de garder la description fournie par les participants. C'est ok que la longueur soit différente. J'ai raccourcie les descriptions trop longues, on pourrait mettre un nombre de caractères max dans le futur si on veut.

A voir si ce ne serait pas plutot le format à adapter. Pourquoi pas passer de la grille à une ligne avec vignette + de la place verticale pour le texte.

Déjà, on a une grille de 2 pour les gagnants et 3 pour les autres contributions. On peut passer à respectivement 1 et 2. 

MAis ça fait le taff en l'état pour moi.
