### ISSUE TITLE
Correction texte sur page d'accueil 

### ISSUE THREAD

**Issue by AlainOttenheimer** [ToulouseDataViz/website#112]
Message de Florian Melki 
J'ai vu sur le site https://toulouse-dataviz.fr/ que mon entreprise est "ENTREPRISE". Peux-tu stp le faire mettre à jour pour mettre "Dernier Cri" à la place stp ?

**Comment by AlainRo** [comment]
Je fais la correction dans Notion (meetup_full) et je profite d'une autre correction (auteur de soumissions) pour faire un rebuild
