### ISSUE TITLE
Lien non fonctionnel 

### ISSUE THREAD

**Issue by AlainOttenheimer** [ToulouseDataViz/website#113]
Meesage de Abdou Diouck
Bonjour
Super intéressants, les propositions.  
J’aimerai juste vous signaler que le lien de ma proposition ne marche pas sur cette  page
https://toulouse-dataviz.fr/hackaviz/2021-results/

c’est https://qpv.geoafrica.fr

Merci

**Comment by AlainRo** [comment]
Corrigé
