### ISSUE TITLE
Acces refusé aux pages html sur serveur ovh TDV

### ISSUE THREAD

**Issue by AlainOttenheimer** [ToulouseDataViz/website#114]
Toutes les pages html hébergées sur le serveur OVH toulouse dataviz  ne sont plus accessibles. Bit defender détecte une page suspecte et ne permet pas l'accès ! 
![Capture](https://user-images.githubusercontent.com/16824227/135754502-e98786f0-b174-452c-98a9-f7a58df072a1.JPG)

Les liens sur le site TDV sont corrects mais si on clique on tombe sur page non trouvée . 
Exemple https://toulouse-dataviz.fr/observablehq/meetup_7_nov_2019/index.html
l'adresse est pourtant bonne. 
Ce qui est étonnant c'est qu'il me semble que ca fonctionnait il y a quelques jours
 
Il est toujours possible d’accéder aux fichiers via filezilla
L'ancien site n'est pas  accessible en mode admin.

**Comment by AlainRo** [comment]
@emaulandi il suffit de transférer le contenu de l'ancien tdv.fr/ dans le nouveau tdv/static (moins les vieux trucs: index.html, ....) OK pour toi ?

**Comment by AlainRo** [comment]
On peut aussi transférer la gestion des DNS sous netlify ce qui permettrait de réactiver le vieux site. (adresse IP ou domaine acheté). A discuter.
