### ISSUE TITLE
Acces aux données hackaviz 

### ISSUE THREAD

**Issue by AlainOttenheimer** [ToulouseDataViz/website#123]
Pour retrouver les données des hackaviz 2021
1 il faut cliquer sur la  "hackaviz"  dans le menu
2 puis descendre au bas de la page et cliquer édition précédente "afficher"
3 puis cliquer sur "voir le hackaviz" sous hackaviz 2021 
4 on accède ensuite a la page du hackaviz avec les données.  
Pas intuitif du tout. 
Ne pourrait on pas accéder a la page https://toulouse-dataviz.fr/hackaviz/editions-precedentes/ directement depuis la page accueil hackaviz?

**Comment by vvivanloc** [comment]
Je te l'accorde, ce n'est pas des plus simples. 

C'est un débat qu'on a eu avec @emaulandi  et @AlainRo.

- version 1 : Edith a mis cette page depuis le lien hackaviz. Dans sa version originale, la page "editions-precedentes" était un peu plus compliquée
- version 2: @AlainRo et moi ont proposé de mettre l'hackaviz de l'année courante plutôt que le "editions-precedentes", pensant que le visiteur serait plus intéressé par le détail de l'hackaviz de cette année. 

Apparemment, tu partages l'avis d'Edith. Balle au centre. 😅
