### ISSUE TITLE
Page concours manquante

### ISSUE THREAD

**Issue by vvivanloc** [ToulouseDataViz/website#127]
Quelqu’un a t il une copie de la page 'Les conditions du concours' : http://toulouse-dataviz.fr/hackaviz-2019-2
Les différents repo GitHub pointent dessus mais la page est non trouvée. 

Il faudrait la mettre sur le nouveau site par exemple à l’adresse : http://toulouse-dataviz.fr/hachaviz/reglement

**Comment by vvivanloc** [comment]
@AlainRo J'ai transformé ta demande en bug

**Comment by vvivanloc** [comment]
Cette page ne figure effectivement pas dans les sources.

@AlainRo 
1/ comment es-tu arrivé à cette addresse  http://toulouse-dataviz.fr/hackaviz-2019-2 ?
2/ est-ce que le contenu LES REGLES/ÉVALUATION  de  cette page https://toulouse-dataviz.fr/hackaviz/2021-contest/ suffirait ?

**Comment by vvivanloc** [comment]
Pour faciliter la création des nouveaux hackaviz, oui, il serait souhaitable de factoriser certaines parties qui se répètent à chaque édition. 

On perd en facilité d'édition (recopier et éditer le mdx) mais on y gagne en efficacité (modifier les propriétés d'un composant React). @emaulandi @AlainRo  Qu'est-ce que vous en pensez ?

**Comment by ToulouseDataViz** [comment]
c'est une page du site wordpress TDV qui n'est plus accessible depuis que le site OVH a été supprimé. On a la sauvegarde du site et il doit être possible de le réinstaller localement. Je n'ai jamais fait cette opération et je n'ai aucune idée de la difficulté...

**Comment by AlainRo** [comment]
La page https://toulouse-dataviz.fr/hackaviz/2021-contest/  convient très bien. Il faut juste la remonter au niveau hackaviz/reglement.
Pour info  http://toulouse-dataviz.fr/hackaviz-2019-2 est réferencée dans le github  Hackaviz2019.
Il y a beaucoup de pages dans les Hackackiz qui n'ont plus de cible.

**Comment by emaulandi** [comment]
_copie de la page 'Les conditions du concours'_ -> pour créer les pages de description de chaque hackaviz (contenant le réglement - légèrement différent à chaque édition) j'avais copié ce qu'il y a avait pour le site historique. Donc on a bien l'historique. Chaque page `...contest` contient le règlement.

Il faut voir si on souhaite en mettre 1 seul : ex dans une page dédié ou dans un composant qu'on peut insérer dans plusieurs page si on le souhaite.

**Comment by AlainRo** [comment]
C'est une possibilité plus précise et non contradictoire avec le règlement unique. J'ai découvert ce problème quand on m'a posé la question : mais quelles sont les conditions de participation ? sous en entendu dans le futur.
Je vote pour la simplicité : un règlement (en fait la dernière mise à jour) et toutes les éditions pointent dessus. Eventuellement on pourrait mettre les règlements en vigueur à chaque édition dans le readme.md sur le github. Adébattre bien sûr.

**Comment by vvivanloc** [comment]
- Les différences entre les concours sont assez minimes pour factoriser les pages de règlement vers une seule source. Mais pour les anciennes éditions, je partage l'avis d'Alain qui souhaite conserver les pages tel quelles 
- J'ai une branche https://github.com/ToulouseDataViz/website/tree/feat/hackavizRules qui contient cette nouvelle page

**Comment by vvivanloc** [comment]
Pour la mise à jour des liens :
 - il faut mettre à jour les readme.md des repo Hackaviz 2018 et Hackaviz 2019 qui pointent vers d'anciens liens.  @AlainRo peux-tu me donner l'accès à ces repo ?
 - pour les autres documents, il faut arriver à trouver un robot qui nous relève tous les liens morts. Va falloir réinstaller Macromedia Dreamweaver :sweat_smile:

**Comment by vvivanloc** [comment]
@AlainRo  Merci pour les accès ! J'ai corrigé les readme.md.

**Comment by AlainRo** [comment]
Merci à toi et joyeux Noël

---
0619655383

**Comment by vvivanloc** [comment]
Joyeux Noël ! :christmas_tree:
