### ISSUE TITLE
Des pages manquantes dans les événements

### ISSUE THREAD

**Issue by AlainRo** [ToulouseDataViz/website#128]
Par exemple https://toulouse-dataviz.fr/meetup_presentation/Poster.pdf
Mais pas que.

Il faut balayer les références et rétablir les fichiers de la sauvegarde de OVH.

**Comment by emaulandi** [comment]
Note des ressources à remetre disponible dans les évènements (peut etre pas encore exhaustif)
- [ ] meetup 35
- [ ] meetup 24
- [ ] meetup 23
- [ ] meetup 22
- [ ] meetup 21
- [ ] meetup 20
- [ ] meetup 15
- [ ] meetup 12
- [ ] meetup 6

**Comment by emaulandi** [comment]
@AlainRo serait-il possible d'être ajoutée comme contributrice à https://github.com/ToulouseDataViz/toulousedataviz.github.io

**Comment by emaulandi** [comment]
@AlainOttenheimer serait-il possible de récupérer la présentation du meetup n°6, à priori à l'adresse http://datasens.fr/demo/Meetup-Ch-Hurter/Meetup DataViz Christophe Hurter 31-05-2016.pdf (403 forbiden) ?
Tu peux la mettre dans le dossier présentation de  https://github.com/ToulouseDataViz/toulousedataviz.github.io, ou je peux la mettre si tu me l'envoie. 
Merci !
