### ISSUE TITLE
Le HackavizFooter est cassé pour les pages ...-data.mdx

### ISSUE THREAD

**Issue by emaulandi** [ToulouseDataViz/website#130]
Il manque juste des quotes sur l'année, je peux m'en occuper

**Comment by vvivanloc** [comment]
hum... merci de me l'avoir signalé. Je m'en occupe.

**Comment by emaulandi** [comment]
@vvivanloc  C'est déjà corrigé dans la branche https://github.com/ToulouseDataViz/website/tree/130-fix-hackaviz-data-page-footer
J'attendais que la MR en cours soit validée pour créer celle-ci.

**Comment by vvivanloc** [comment]
En effet, j'ai vu la branche eb faisant un git fetch.

**Comment by vvivanloc** [comment]
la PR est ici : https://github.com/ToulouseDataViz/website/pull/131

**Comment by vvivanloc** [comment]
J'ai validé la PR. Merci !
