### ISSUE TITLE
Récupérer le rich text Notion présent dans les champs plutôt que le sur-markdown

### ISSUE THREAD

**Issue by AlainRo** [ToulouseDataViz/website#21]
Notion permet de formatter les champs (gras, italique, barré, souligné) sans avoir recours au markdown explicite : exemple les  meetups.
J'ai pas vraiment de solution voir [Notion-x](https://github.com/NotionX/react-notion-x) peut être.

**Comment by emaulandi** [comment]
Normalement c'est bien pris en charge aujourd'hui avec un plugin custom supplémentaire` gatsby-plugin-md-from-notion-table-attribute`, qui va chercher l'attribut description (`properties.description?.value`) et en créé un noeud markdwon définit comme un enfant de l'évènement en question. Voir https://github.com/ToulouseDataViz/website/blob/main/plugins/gatsby-plugin-md-from-notion-table-attribute/gatsby-node.js
Voir par exemple le résultat sur la page https://tdv-site.netlify.app/meetup/48)

**Comment by emaulandi** [comment]
il y a cependant parfois des petits loupés à cause des espaces, par exemple :
![image](https://user-images.githubusercontent.com/16479203/128192042-cf291faf-0c31-4364-bc28-6bef34e19f2a.png)
![image](https://user-images.githubusercontent.com/16479203/128192104-70a26ffa-de30-458d-8771-ce530d785172.png)

**Comment by AlainRo** [comment]
👍 J'ai retiré quelques markdown explicite pour voir ce que cela donne.

**Comment by AlainRo** [comment]
Closed ?
