### ISSUE TITLE
Les livres

### ISSUE THREAD

**Issue by ToulouseDataViz** [ToulouseDataViz/website#28]
La description est souvent tronquée et il n'existe pas de moyen de la déployer.
Priorité : basse

**Comment by AlainRo** [comment]
C'est AlainRo l'auteur de la précédente remarque

**Comment by emaulandi** [comment]
Oui, j'ai bien ça en tête. Comme le texte est long, j'avais prévu de faire une versio  courte "coupé" pour bien voir tous les livres + 1 page par livre avec tout le contenu (les datas sont là, faut juste dupliquer le fonctionnement utilisé pour les meetups)

**Comment by emaulandi** [comment]
@AlainRo après via react on peut faire du tri ou autre assez sympa (c'est du bonus)

![image](https://user-images.githubusercontent.com/16479203/128485080-fd2b264d-eb13-494e-8792-20ec8c783d8d.png)
