### ISSUE TITLE
Doesn't work out of the box

### ISSUE THREAD

**Issue by AlainRo** [ToulouseDataViz/website#31]
J'ai cloner le repo pour essayer des trucs en local et j'ai une erreur de non reconnaissance du safe navigation operator ?. dans un plugin. npm run develop ou build ?????? 

Quelle version de node et de npm utilises tu ? Qu'est ce que ça peux être d'autre ?

**Comment by emaulandi** [comment]
Est-ce que tu peux copier-coller l'erreur en entier ? Je n'ai jamais vu ça encore

Je vais mettre à jour le readme avec plus d'info :
- Node : v14.15.0
- NPM : 7.19.1
- Gatsby : v3.3.0 (indiqué dans le package.json)
- Créer des fichier `.env.development` et `.env.production` sur le modele de `.env` avec les bonnes infos

Je ne sais pas si ça joue, tu peux directement utiliser `gatsby develop` mais c'est équivalement à `npm develop` normalement

**Comment by emaulandi** [comment]
Oui la V14 est chouette pour pouvoir utiliser `.?` : https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by emaulandi** [comment]
J'ai mis à jour le readme : https://github.com/ToulouseDataViz/website/blob/main/README.md
