### ISSUE TITLE
Tester la migration vers gatsby-source-notion pour comparer le temps de build

### ISSUE THREAD

**Issue by emaulandi** [ToulouseDataViz/website#33]
https://github.com/alvis/gatsby-source-notion

Apparement plus court et permet de requêter plusieurs databases et pages

Actuellement le plugin gatsby-source-notion-api -> build de 5min envion

**Comment by emaulandi** [comment]
@AlainRo pour info 

Voir la branche 33 -> https://github.com/ToulouseDataViz/website/commit/7b851ac1e4856ed0bf9aad58a5a1536716dbf2a8

**Avantages** :
- Une fois qu'on a compris le fonctionnement, facile de requêter plusieurs databases et pages
- Buildtime total 105 secondes VS 249s actuellement (test des build en local)

**Note** : Conséquence d'un avantage : si on a un traitement différencié selon les database, il faut bien filtrer sur leur nom, adapter les requêtes GraphQL par rapport au fonctionnement à une seule base de données

**Désavantage** :
- Pas d'accès au texte "raw" de la description, le format est celui fournit par l'API de Notion en 'rich_text' sous un format non standard (pas facile à parser pour le rendre). On doit alors récupérer le noeud Markdwon généré à partir du noeud NotionPage, c'est le seul qui a le texte "raw" pour ensuite créer un noeud markdwon à partir de cette valeur.
Doit y'avoir plus simple mais j'ai pas encore trouvé.
- On perd des infos du markdwon, le style implicite est perdu dans l'attribut du noeud Markdwon
![image](https://user-images.githubusercontent.com/16479203/128385786-b0a2da3f-8fa6-4e29-ab84-82c909a82c46.png)
![image](https://user-images.githubusercontent.com/16479203/128385864-f59fb48f-e0ee-477c-98b0-eff9630c15bc.png)

**Comment by AlainRo** [comment]
OK cela parait cool, je vais regarder de plus près.
Pour le rendu des formats Notion il y a : https://github.com/NotionX/react-notion-x pas encore testé en direct mais c'est le coeur du système de publication des newsletters.toulouse-dataviz.fr

**Comment by emaulandi** [comment]
Yes merci !

En fait je fait beaucoup trop compliqué je crois, comme Notion fournit déjà ce format RichText, faut plutot chercher à le formatter directement et pas en recréer un noeud markdwon je pense. Je vais voir chez react-notion-x comment ils formattent ça !

**Comment by emaulandi** [comment]
On veut pouvoir à la fois gérer le rich text de notion d'éventuel titre / lien markdwon

A priori les liens pourrait être géré par Notion (ajouter un lien) mais pas les titres
![image](https://user-images.githubusercontent.com/16479203/128498010-070967f4-8183-4fae-8c44-23e3ef169075.png)
![image](https://user-images.githubusercontent.com/16479203/128498076-cf2ac958-acca-4ad9-b413-06a3df5da6b5.png)

**Comment by emaulandi** [comment]
Mais avoir les deux en // fout un peut le bordel

Par exemple :
![image](https://user-images.githubusercontent.com/16479203/128499487-925d72c0-a089-4259-8b1d-7c9c8a71a2f7.png)

Donne
![image](https://user-images.githubusercontent.com/16479203/128499467-0d35b03c-b6ab-4b71-b0bd-f3287e0b0d1e.png)

**Comment by emaulandi** [comment]
Résumé :

**Option 1** : on utilise uniquement le rich text notion pour les champs description (ou autre) dans une databse. Cela supporte les liens, et tous les types d'annotations de texte : gras, code, couleur, italique, souligné, barré. On rajoute un composant qui prend en entrée du rich text et le formatte pour le site (comme le composant MarkdwonText le fait pour le format htmlAst aujourd'hui)

**Option 2** : on fait du 100% markdwon pour pouvoir supporter les titres également (ex: page de Les rencontres de la dataviz où on veut pouvoir détailler plus). Cela demande, dans le plugin custom existant, de créer un noeud markdwon à partir du texte pur en markdwon. Mais c'est relou parce quand on renseigne une description, il faut faire echap pour désactiver le formattage richtext automatique (au lieu de **texte**, le texte se met en gras directement)

**Comment by emaulandi** [comment]
@AlainRo ça t'irait si pour l'instant on prend l'option 2 pour bénéficier de ce nouveau plugin qui permet un build plus rapide ?
(note: la description de tous les meetups est déjà en mode mardown "explicite")

**Comment by AlainRo** [comment]
Oui OK pour Option 2. 

Pour info react-notion-X fait appel à sa propre API Notion non officielle et ne parait pas directement connectable aux données issues de l'API officielle.

**Comment by emaulandi** [comment]
Oui puis ça à l'air top mais déjà très "formatté" visuellement. Nous on fait du cherry picking d'info et on a une mise en forme perso pour le site.

**Comment by emaulandi** [comment]
On gagne un peu en temps, mais c'est pas drastique non plus : 
![image](https://user-images.githubusercontent.com/16479203/128506912-03480a08-df25-47eb-883e-efc9490f8001.png)

Par contre j'ai regardé dans l'historique, et j'ai l'impression que c'est l'ajout des livres qui a rajouté du temps de build, ça doit être lié au préprocessing des images (moyenne autour de 50 kB)
![image](https://user-images.githubusercontent.com/16479203/128507008-5720e23b-7acc-49ef-b104-cd9633b2651c.png)
