### ISSUE TITLE
Découper la page ressources ? 

### ISSUE THREAD

**Issue by emaulandi** [ToulouseDataViz/website#35]
Différencier Newsletter / Collections / Offres

⇒ 4 rubriques sur 4 pages séparées
    - Newsletters (en page par défaut)
    - Collection de dataviz ← trouver le bon nom
    - Posters
    - Livres

**Comment by vvivanloc** [comment]
A mon avis, cette page est beaucoup trop longue. Il faudrait la découper en petits morceaux.
Trop d'info tue l'info :(.

**Comment by vvivanloc** [comment]
Dans la version courante, il y a un double lien qui pointe sur collection et sur newsletter

**Comment by emaulandi** [comment]
Il y a déjà une issue ouverte sur le sujet

**Comment by AlainRo** [comment]
Ce qui est certain : Les newsLetters sont gérées sur Notion2site. C'est le seul moyen d'avoir une mise en page quasi-libre et la possibilité à un débutant complet de rédiger ou corriger son article.

Après il est possible de gérer de la même manière les posters, collections et livres, ... qui peuvent rentrés dans le même moule (une synthèse en galerie, je click dessus et je découvre le contenu) .... ou pas. 

Il est possible de structurer en plusieurs pages Notion la page ressources. Pas très joli mais gratuit à faire. 

Pour avoir une page racine avec url propre pour chaque rubriques (newsletters.toulouse-dataviz, posters.toulouse-dataviz, ...) il faut répliquer notion2site autant de fois (pas très glop mais faisable). 

ATTENTION : La décision ne doit pas seulement prendre en compte l'aspect visuel final mais aussi le temps/coût de modification ET la facilité de mise à jour.

**Comment by emaulandi** [comment]
Je pense que le commentaire de @vvivanloc concerne le site Gatsby où sur la page http://new.toulouse-dataviz.fr/ressourcescollections il y a à la suite Newsletter, Collections, Livres.

**Comment by emaulandi** [comment]
Sur Gatsby : 1 seul encart Ressource vers notion2site
- 1 bouton
- 1 iframe
