### ISSUE TITLE
logo carre sans fond png 

### ISSUE THREAD

**Issue by AlainOttenheimer** [ToulouseDataViz/website#38]
![Logo_toulouse_Dataviz-carre(2)](https://user-images.githubusercontent.com/16824227/128500267-a0f2bc58-e52a-4379-a950-26b231532f90.png)
![Logo_toulouse_Dataviz-carre](https://user-images.githubusercontent.com/16824227/128500275-bc57454e-acd9-4aa2-a254-3a8faf29cae0.png)

**Comment by emaulandi** [comment]
duplication #24
