### ISSUE TITLE
ajouter logo la mêlée dans les sponsors de l'hackaviz 2021

### ISSUE THREAD

**Issue by AlainOttenheimer** [ToulouseDataViz/website#39]
![Logo Melee](https://user-images.githubusercontent.com/16824227/128501372-64acc9dd-f835-40ec-b7fa-fd919f208528.jpg)

**Comment by emaulandi** [comment]
@AlainOttenheimer  pour les prochains, si tu veux t'essayer ce n'est vraiment pas difficile : https://github.com/ToulouseDataViz/website/commit/824458f9b2c51f09f38d7a9a71356f6a074171a2
