### ISSUE TITLE
revoir la table meetups_full 

### ISSUE THREAD

**Issue by AlainOttenheimer** [ToulouseDataViz/website#42]
Revoir la table notion meetups_full
La table notion n'est pas éditable en l'état. il manque
- tous les liens vers les présentations,
- des mises à la ligne sont manquantes. 
- markdown  caractères gras manquant et uniformiser les règles 
- texte  a été tronqué
- texte lien vidéo n'ont pas été supprimé du texte
- .....  
Sans preview c'est pas simple

**Comment by emaulandi** [comment]
Pour simplifier le processing du contenu, la règle est d'uniformiser au format Markdown "visible" ex: `**mot en gras**`

Comme un meetup peut avoir plusieurs présentation, je propose de le garder en tant que texte avec un line explicite `[texte du lien](url)` dans le champ présentation

**Comment by emaulandi** [comment]
@AlainOttenheimer tu pense que tu peux faire les modifs où tu as besoin d'aide ?

**Comment by AlainOttenheimer** [comment]
Il faut tout reprendre meetup par meetup manuellement sans possibilité de préview.  J'assure pas sur ce coup là. Qui s'était engagé sur ce tableau ?

**Comment by emaulandi** [comment]
Cela reste assez prévisible sous format Markdown :
- pour faire un saut à la ligne, rajouter un saut à la ligne
- pour faire un lien, rajouter `[texte du lien](url)`
- pour rajouter du gras, rajouter les doubles *"visible" ex: `**mot en gras**`

**Comment by emaulandi** [comment]
J'ai rajouté dans notionun exemple en vidéo pour les meetups 33 et 34, voir la page documentation

**Comment by AlainRo** [comment]
Tout à fait d'accord (pour le moment, on verra à améliorer plus tard) avec le processus proposé par Edith.
Les exemples meetups #33 et #34 sont parfaits. (liens externes)
Mais il y a aussi le cas des présentations en powerpoint ou pdf directement hostés sous Worpress (tu confirmes @AlainOttenheimer ?). Pour ces cas on a trois solutions : 
 1. on les laisse sur OVH mais ca suppose de conserver l'URL
 2. on les transfère sur Notion et on récupère les liens aws des fichiers un par un
 3. on les met sur Github et on récupère les liens un par un

**Comment by emaulandi** [comment]
On doit pouvoir faire 3 + gestion par gatsby en effet. Après, il y en a plusieurs sur Speaker Deck, donc on peut imaginer centraliser les présentation dessus aussi par exemple.

**Comment by ToulouseDataViz** [comment]
les ppt et pdf sont sur speaker desk sauf exception. 
Sur OVH les fichiers des hackaviz, covidoscope et quelques autres trucs type reveal, j'imagine. 
La page événement est THE page du site. Reporter des taches à la saint  ginglin , c'est la garantie que la mise à jour va trainer pdt des mois (voir bilan annuel) parce que personne voudra faire le taff.

**Comment by emaulandi** [comment]
Pour les évènements, il reste à seulement à migrer vers spekerDeck 10 présentations environ et on est opérationnel, voir notion pour s'organiser pour cela

**Comment by emaulandi** [comment]
si la vidéo explicative pour mettre à jour le champ **description** des meetups n'est pas assez claire, je m'occuperais de le faire

**Comment by emaulandi** [comment]
J'ai refait une passe sur tous les meetups, j'ai rajouté dans les descriptions les liens des présentations manquantes, et mis mieux en forme que sur le site actuel.
