### ISSUE TITLE
Améliorer le temps du build du site

### ISSUE THREAD

**Issue by emaulandi** [ToulouseDataViz/website#43]
Objectif : économiser nos minutes gratuires par mois chez Netlify

pour info @AlainRo 

- [x] 1 - Utilisation du plugin `gatsby-source-notion`
- [x] 2 - Activation du plugin gatsby chez Netlify pour garder le cache entre les builds
- [ ] 3 - Voir si le build incrémental est possible (on ne reprocess pas ce qui n'a pas changé, notamment les images), à priori que quand les sources de données sont des cms partenaires

2 semble très efficace
![image](https://user-images.githubusercontent.com/16479203/128565967-ba4c4feb-7544-4dac-aac3-38a5f3d1adb4.png)

**Comment by vvivanloc** [comment]
Quelques achtuches: https://www.gatsbyjs.com/docs/how-to/performance/improving-build-performance/

**Comment by vvivanloc** [comment]
Quelques timings gatsby clean+build sur  ma vieille machine: 
-  building in 169s
   -  bootstrap - 29s
        - source and transform nodes - 16s
        - run page queries - 3s 
   - building production JavaScript and CSS bundles - 80s
   - building HTML renderer - 17s
   - caching JavaScript and CSS webpack compilation - 51s
   - caching HTML renderer compilation - 35s

**Comment by vvivanloc** [comment]
fixed by updated some gatsby deprecated dependencies
