### ISSUE TITLE
Relecture site 

### ISSUE THREAD

**Issue by AlainOttenheimer** [ToulouseDataViz/website#45]
**[OK]** _Mettre un lien discord plutôt que Slack qui n'est pas accessible directement ?_  

**[OK]**  _Page événement :  ajouter les présentations_
_- Venez découvrir de nouveaux sujets autour de la visualisation de données, en présentiel ou à distance ! Vous pouvez revoir **les présentations**_ et les vidéos de plusieurs évènements passés._

**[OK]** _Page Hackaviz 2020, les 4 boites préparer l'hackaviz se touchent_

**[OK]** _Rafraichissement des pages. 
l'ouverture de page produit des affichages étranges pour les logos des sponsors qui apparaissent sans fond blanc mais en faisant un refresh l'affichage redevient correct. C'est quasi sytématique sur ma machine avec firefox sur toutes les pages avec les logos
(pour info cache nettoyé au préalable)_

**[OK]** _Je propose que l'on écrive systématiquement Toulouse DataViz avec V majuscule_ 

**[OK]** _Page association, Notre offre, L'association Toulouse Datavi est soutenue...  (manque le z)_

Photo Ch Regouby et Tony manquantes + liens -> #11 

Nos offres formation - On pourrait mettre la photo de vincent  pdt le PLC31  -> fournir la photo dans #12 @AlainOttenheimer 

Suggestions  a discuter : Ressources et collections en 2 pages 
1 page ressources Newsletter + livres 
1 page collection  

**[OK]** _La page Club n'apparait pas dans le menu_ 
**[OK]** _Je propose de ne pas mettre de photos dans la page club ou peut être juste une_

**Comment by emaulandi** [comment]
Certaines modifications peuvent être réalisée facilement via l'interface graphique de Github (création d'une branche, modification, création d'une pull request, vérification de la preview, mege)

Pour les mebres : suivre la Documentation sur notion:
- ajouter les infos dans le csv : `src/data/membres.csv`
- si le champ `pic_name` est renseigné, s'assurer qu'on ajoute une photo avec ce nom dans  `src/content/pics/team-pics`

Pour les fautes d'orthographes sur des pages : modifier la page dans `src/pages` :
- pour l'association : https://github.com/ToulouseDataViz/website/blob/main/src/pages/association.mdx
- pour les évènements : https://github.com/ToulouseDataViz/website/blob/main/src/pages/evenements.mdx

**Comment by emaulandi** [comment]
Rafraichissement des pages. -> #46

**Comment by emaulandi** [comment]
Nos offres formation On pourrait mettre la photo de vincent pdt le PLC31 -> fournir la photo dans #12

**Comment by emaulandi** [comment]
Je propose de ne pas mettre de photos dans la page club ou peut être juste une -> je propose de mettre la gallery en dessous du texte

**Comment by emaulandi** [comment]
[OK] La page Club n'apparait pas dans le menu

**Comment by emaulandi** [comment]
[OK] Page événement : ajouter les présentations

    Venez découvrir de nouveaux sujets autour de la visualisation de données, en présentiel ou à distance ! Vous pouvez revoir les présentations_ et les vidéos de plusieurs évènements passés.

**Comment by emaulandi** [comment]
**[OK]** _Mettre un lien discord plutôt que Slack qui n'est pas accessible directement ?_

**Comment by emaulandi** [comment]
**[OK]** _Page association, Notre offre, L'association Toulouse Datavi est soutenue...  (manque le z)_

**Comment by emaulandi** [comment]
Photo Ch Regouby et Tony manquantes + liens -> #11
