### ISSUE TITLE
Rajouter vignette evenement dans la vue en grille (Events.js)

### ISSUE THREAD

**Issue by emaulandi** [ToulouseDataViz/website#48]
- [x] Créer un champ texte vignette dans la bdd notion meetup full
- [x] Récupérer les vignettes depuis le site meetup
- [x] Remplir  la bdd notion meetup full avec la convention de nommage meetup_vignette_[id du meetup] pour les events dont on a une vignette
- [ ] Ajouter les vignette dans un dossier spécifique sous `src/content/pics`
- [ ] Adapter la requette graphql du hook `useEventNotion` pour récupérer le champ vignette
- [ ] Adapter le composant Event pour mettre un composant GatsbyImage si le champ vignette n'est pas null

@AlainRo pour info

**Comment by AlainRo** [comment]
OK pas mal. Mais pourquoi ne pas mettre un vrai lien vers la vignette. Interne sur github ou externe n'importe où ailleurs y compris sur meetup ou Notion ?

**Comment by AlainRo** [comment]
Ce serait plus général et efficace.

**Comment by emaulandi** [comment]
A voir si c'est utilise pour savoir où les récupérer, une fois "digérée" par GatsbyImage, on peut les récupérer facilement avec juste leur nom.

**Comment by vvivanloc** [comment]
@emaulandi Salut, tu peux pousser pour que je puisse reprendre ?

**Comment by emaulandi** [comment]
J4avais pour l'instant "juste" collecté les vignettes meetups (les images), je te retrouve ça.

**Comment by vvivanloc** [comment]
done
