### ISSUE TITLE
Découper la page Hackaviz ?

### ISSUE THREAD

**Issue by vvivanloc** [ToulouseDataViz/website#74]
actuellement : page regroupant l'hackaviz actuel, les précédents et le concept

trop long ? à découper ?

⇒ 3 rubriques
    - Hackaviz en cours (en page par défaut)
    - Hackaviz précédents
    - Concept

Pour moi l'objectif de cette page : aller voir les dernières news du hackaviz courant ou afficher les gagnants des anciens hackaviz ? en v2.0, on pourrait mettre une galerie (une pu comme celle de la page d’accueil) pour "l'incentive"

**Comment by vvivanloc** [comment]
Avis d'Edith: ça permet de voir tous les gagnants en une seule page, toujours en ayant le meetup le plus récent en premier. C'est dommage de devoir aller dans chaque meetups pour voir les soumissions majeures je trouve. Là ça à l'avantage de mettre en avant les gagnants depuis le début et les vidéos de remises des prix, pour engager les personnes à explorer plus.

l'objectif de la page est d'avoir un vue d'ensemble de ce qu'est le hackaviz et des éditions passées et devoir du concret sur les réalisations. Les news du hackaviz courant c'est que 10 jours par an (un peu plus avec la remise des prix), donc ce n'est pas le focus de cette page, à priori, on peut toujours faire évoluer cela, ou mettre le hackaviz courant en avant sur la page d'accueil le temp de l'évènement aussi

**Comment by emaulandi** [comment]
A noter, en plus de cette page princiaple, chaque hachaviz a sa page de présentation, sa page de données et sa page de réalisations soumises.

**Comment by emaulandi** [comment]
Proposition : arriver sur la page du hackaviz en cours (si fini : aller siur la page de résultat, sinon la page de description)
Supprimer page d'overview de tous les hackaviz

**Comment by emaulandi** [comment]
Pistes : à partir de hackaviz.csv, trouver le "dernier" hackaviz en date. 
https://github.com/ToulouseDataViz/website/blob/main/src/data/hackaviz.csv
(d'ailleurs, le status du 2021 ne devrait être à Réalisé que quand on aura publié les résultats)

En fonction de s'il est fini ou non, définir la page où rediriger (si pas fini -> /hackaviz/[annnée]-contest, si fini -> /hackaviz/[année]-results)

**Comment by vvivanloc** [comment]
Oui, j'ai vu. Mais je propose d'afficher directement la page hackaviz 2021. 
Ensuite, dans cette page, il y a un footer commun aux autres pages hackaviz qui permet d'aller sur la page overview que tu as faite / revenir à la page principale.
J'ai simplifié la page overview en ne présentant que les lauréats.
J'ai aussi promus  la section  concept dans sa propre page.

Tous les changements en WIP sont sur cette branche : https://github.com/ToulouseDataViz/website/tree/fix/hackaviz

**Comment by vvivanloc** [comment]
Bonjour. 
Vous en pensez quoi ?
A vous de valider la PR ou non. Pour cela, vous pouvez voir la modif sur https://deploy-preview-97--tdv-site.netlify.app//

**Comment by vvivanloc** [comment]
En v2.0, comme toutes les pages se ressemblent, il serait intéressant de les générer automatiquement ?

![image](https://user-images.githubusercontent.com/7536295/133921527-608b77ee-5804-4607-87e5-016569b4e4e3.png)

- 20xx-contest: depuis un CSV ?
- 20xx-results: déjà fait, merci Edith ! :+1: 
- 20xx-data: dupliquer le readme de GitHub, bof - info dupliquée toussa :cry: . Est-ce qu'il ne faudrait pas mieux laisser un lien vers GitHub?

@emaulandi  Je ne sais pas s'il est possible de remplacer toutes ces pages par des pages "virtuelles" ?

**Comment by vvivanloc** [comment]
En faisant mumuse avec le plugin Books, j'ai trouvé CreatePage qui devrait faire le job.

**Comment by emaulandi** [comment]
Il ya plusieurs options et plsuieurs aspects :
- avoir un composant React qui génère le contenu à partir de données : c'est le cas de HackavizResults ou HackavizSponspors
- la création des pages, se fait au moment du build par Gatsby, voir les plugins https://github.com/ToulouseDataViz/website/tree/main/plugins

**Comment by emaulandi** [comment]
_Oui, j'ai vu. Mais je propose d'afficher directement la page hackaviz 2021._
Oui je comprend bien, mais il est plus propre à mon sens de garder des conventions de nommage identique pour tous les hackaviz (results, contest, data ect..) et gérer ce qui est affiché uniquement dans les redirections : quand je clique sur hackaviz dans le menu, ça me redirige vers 2021-contest par exemple. Cette redirection peut etre programmatique en fonction de l'année et du statut du hackaviz, pour ne pas avoir à modifer la page hackaviz.mdx à chaque changement de hackaviz surtout.

**Comment by emaulandi** [comment]
_dupliquer le readme de GitHub, bof - info dupliquée toussa_ -> pour le hackaviz 2021, on source directement le contenu de github
mais oui on pourrait faire le lien direct sur github et ne pas avoir de page _data pour les hackaviz, moi ça me va

**Comment by vvivanloc** [comment]
ok pour la convention de nommage, au lieu d'inverser le contenu des pages hackaviz et editions_precedentes (overview), je modifierai le lien vers le menu.
