### ISSUE TITLE
Améliorer la présentation de "Nos offres"

### ISSUE THREAD

**Issue by vvivanloc** [ToulouseDataViz/website#78]
la photo actuelle de l'offre utilisée sous Notion -> ne pas hésiter à la remplacer

M'enfin ?! C'est quoi ce truc ?!
![image](https://user-images.githubusercontent.com/7536295/132123938-42ff7bcb-7d9c-43c0-be3a-1227073a30ec.png)

@AlainOttenheimer @AlainRo Vous avez un truc plus "spectaculaire" qu'un parallel plot ?

**Comment by AlainRo** [comment]
C'est un slope chart qui met en évidence les évolutions comparées de plusieurs grandeurs? J'assume totalement et j'aimerai en voir plus souvent. 😜
Et il faut se méfier du "spectaculaire". 😊
