### ISSUE TITLE
Ressources et collections : améliorer l'UX du filtre de livres

### ISSUE THREAD

**Issue by vvivanloc** [ToulouseDataViz/website#79]
- Éviter de tout décocher ? 
![image](https://user-images.githubusercontent.com/7536295/132124072-f848249d-e0d6-4058-8a2d-ee50590f4065.png)

**Comment by emaulandi** [comment]
C'est à dire ?

Par défaut, on affiche tous les livres, et on laisse la possibilité à l'utilisateur de cocher / décocher ce qu'il.elle souhaite pour explorer les livres.

**Comment by emaulandi** [comment]
Livres hargés sur notion2site
