### ISSUE TITLE
Https ?

### ISSUE THREAD

**Issue by AlainRo** [ToulouseDataViz/website#86]
Pas vraiment une urgence mais ce serait bien d'avoir un certificat https.

**Comment by vvivanloc** [comment]
Y'a bien https://letsencrypt.org/fr/ mais à l'époque il fallait renouveler le certif tous les 4 mois :(

**Comment by AlainRo** [comment]
Il doit y avoir une option depuis Netlify. Ou alors depuis OVH.

**Comment by vvivanloc** [comment]
Hum... après réflexion, c'est important. ça peut faire peur à Mme Michu :) 
![image](https://user-images.githubusercontent.com/7536295/132989546-b9c45558-9a88-49fd-b593-802563d1ff90.png)

**Comment by AlainOttenheimer** [comment]
J'ai eu un message de ce type lorsque j'ai cliqué sur "retour au site" depuis la page "les ressources de Toulouse dataviz : Bit defender - page suspecte URL dangereuses...

**Comment by AlainRo** [comment]
J'ai remplacé https par http dans le lien 'Retour au site'. Cela devrait calmer les messages d'erreurs.

**Comment by AlainRo** [comment]
Moins facile à faire qu'il n'y parait : étudier https://cheapsslsecurity.com/blog/ssl-certificates-for-subdomains/

**Comment by AlainRo** [comment]
Fonctionnel
