### ISSUE TITLE
Mettre à jour la galerie

### ISSUE THREAD

**Issue by vvivanloc** [ToulouseDataViz/website#89]

**Comment by vvivanloc** [comment]
voir avec xtophe où sont les photos

**Comment by emaulandi** [comment]
@vvivanloc Christophe a déjà contribué aux photos, je ne sais pas s'il y en d'autres. Les photos des meetups sont dans https://github.com/ToulouseDataViz/website/tree/main/src/content/pics/meetup-pics et le composant gallery en prend au hasard dedans pour l'instant https://github.com/ToulouseDataViz/website/blob/main/src/components/Gallery.js#L61

Quelle est la mise à jour dont tu parles ?

**Comment by vvivanloc** [comment]
Oui, je n'avais pas vu. Je pensais que xtophe nous avait posé des milliers de photos 😁
