### ISSUE TITLE
"Livres" plutôt que "Copy of Livres"

### ISSUE THREAD

**Issue by AlainOttenheimer** [ToulouseDataViz/website#94]
lorsque l'on clique sur livres dans ressources : "Copy of Livres" s'affiche

**Comment by AlainRo** [comment]
Devrait être corriger

**Comment by vvivanloc** [comment]
Bizarre, ça n'a été encore déployé sur le site. Le robot vercel est en week-end ? :crying_cat_face: 
Capture au dimanche 19 septembre
![image](https://user-images.githubusercontent.com/7536295/133921009-e7e9afe9-9bab-4dbe-92ce-fdfb402c762a.png)

**Comment by AlainRo** [comment]
Oui je sais je force un rebuild pour les tous impatients :-)

**Comment by vvivanloc** [comment]
Corrigé - merci !
